import myutil;
import three;
size(8cm, 0);
dot(2Y, white);
dot(1.7Z, white);
draw(-1.5X -- 1.5X, arrow=Arrow3(TeXHead2), L=Label("$x_1$", position=EndPoint, align=W));
draw(-1.5Y -- 1.5Y, arrow=Arrow3(TeXHead2), L=Label("$x_2$", position=EndPoint));
draw(-1.5Z -- 1.5Z, arrow=Arrow3(TeXHead2), L=Label("$x_3$", position=EndPoint));
draw(unitsphere, surfacepen = material(green+opacity(0.5)));
label("$f(\bm{x}) = \|\bm{x}\|^2 = c$", -1.1Z, SE, heavygreen);
ship();
triple p = rotate(10,Y)*rotate(-40,X)*Z;
dot(p);
label("$\bm{x}^*$", p, E);
ship();
draw(rotate(10,Y)*rotate(-40,X)*shift((-1,-1,1))*scale3(2)*unitplane, surfacepen = blue+opacity(0.5));
label("Tangent plane $T_{\bm{x^*}}$", 1.2Z+0.1*X);
ship();
draw(rotate(10,Y)*rotate(-40,X)*(Z--2Z), linewidth(1), Arrow3(10));
label("$\nabla f(\bm{x}^*)$", rotate(10,Y)*rotate(-40,X)*2.2Z);
ship();
