size(550,0);
import myutil;

draw(box((-1.6,-2.1),(19.5,2.1)),white);
label("$\bm{x}\sim \mathcal{D}$", (0,0), W);
ship();
draw((0,0)--(1,0), MidArrow);
draw((1,-2)--(1,2)--(4,0.5)--(4,-0.5)--cycle);
label("Encoder", (2.5,0.4));
label("(parameters $\bm{\phi})$", (2.5,-0.3));
draw((4,0)--(5,0), MidArrow);
ship();
real a = 5;
real b = a + 1.5;
label("$(\bm{\mu}, \bm{\sigma})$", (0.5*(a+b),0));
real c = b + 1;
ship();
draw((b,0)--(c,0), MidArrow);
real d = c + 2.5;
label("$z\sim q_{\bm{\phi}}(\bm{z}| \bm{x})$", (0.5*(c+d),0));
ship();
label("$q_{\bm{\phi}}(\bm{z}| \bm{x})=\mathcal{N}(\bm{z}|\bm{\mu},\mathrm{diag}(\bm{\sigma}^2))$", (0.5*(c+d),-1.5));
ship();
draw((d,0)--(d+1,0), MidArrow);
draw((d+1,-0.5)--(d+1,0.5)--(d+4,2)--(d+4,-2)--cycle);
label("Decoder", (d+2.5,0.3));
label("(parameters $\bm{\theta})$", (d+2.5,-0.3));
draw((d+4,0)--(d+5,0), MidArrow);
real f = d+5;
real g = f+1;
label("$\hat{\bm{x}}$", (0.5*(f+g),0));
ship();
draw((g,0)--(g+1,0), MidArrow);
label("$p_{\bm{\theta}}(\bm{x}|\bm{z})$", (g+1,0), E);
ship();
label("$=\mathcal{N}\left(\bm{x}-\hat{\bm{x}}\big|\bm{0}, \sigma_e^2\, \mat{I}\right)$", (d+5,-1.5), E);
ship();
